import React from 'react'


export const metadata = {
  title: "Terms-Conditions | Chop-Life Shawarma",
  description: "Generated by create next app",
};

const layout = ({children}) => {
  return (
    <>
      {children}
    </>
  )
}

export default layout
